# Generated by Django 5.1 on 2024-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_subscription_alter_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokhitmovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='epaperdaily',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-date']},
        ),
    ]
